development:
  adapter: postgresql
  encoding: unicode
  database: recipe_organizer_development
  host: localhost
  pool: 5
  username: recipe_organizer
  password: feedlotrat

test:
  adapter: postgresql
  encoding: unicode
  database: recipe_organizer_test
  host: localhost
  pool: 5
  username: recipe_organizer
  password: feedlotrat
